AWSTemplateFormatVersion: '2010-09-09'
Description: Aurora MySQL DB

Parameters:
  Subnet1Id:
    Type: String
  Subnet2Id:
    Type: String
  DBSecretArn:
    Type: String
  DBName:
    Type: String
    Default: imageprocessing
  EC2SecurityGroupId:
    Type: String

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for Aurora"
      SubnetIds:
        - !Ref Subnet1Id
        - !Ref Subnet2Id

  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineVersion: 5.7.mysql_aurora.2.12.5
      EngineMode: provisioned
      DatabaseName: !Ref DBName
      MasterUsername: !Sub '{{resolve:secretsmanager:${DBSecretArn}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBSecretArn}:SecretString:password}}'
      DBSubnetGroupName: !Ref DBSubnetGroup
      BackupRetentionPeriod: 1
      StorageEncrypted: false
      VpcSecurityGroupIds:
        - !ImportValue "VPCStack-SecurityGroupDB"
        - !Ref EC2SecurityGroupId

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceClass: db.t3.small
      Engine: aurora-mysql
      PubliclyAccessible: false

  DBNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /image-processing/db-name
      Type: String
      Value: !Ref DBName

  DBEndpointParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /image-processing/db-endpoint
      Type: String
      Value: !GetAtt DBCluster.Endpoint.Address

  DBSecretArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /image-processing/db-secret-arn
      Type: String
      Value: !Ref DBSecretArn

Outputs:
  DBClusterEndpoint:
    Value: !GetAtt DBCluster.Endpoint.Address
  DBClusterId:
    Value: !Ref DBCluster
  DBSecretArn:
    Value: !Ref DBSecretArn