AWSTemplateFormatVersion: '2010-09-09'
Description: Image Processing Main Stack

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cursor.style/vpc.yaml

  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cursor.style/storage.yaml

  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cursor.style/ecs.yaml

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: StorageStack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cursor.style/lambda.yaml

  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cursor.style/db.yaml
      Parameters:
        Subnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        Subnet2Id: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
        DBSecretArn: !GetAtt StorageStack.Outputs.SecretArn